// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: corona-warn-companion/src/main/java/org/tosl/coronawarncompanion/gmsreadout/ContactRecords.proto

package org.tosl.coronawarncompanion.gmsreadout;

public final class ContactRecordsProtos {
  private ContactRecordsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScanRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gmsreadout.ScanRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    int getTimestamp();

    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     * @return Whether the rssiMultipleValues field is set.
     */
    boolean hasRssiMultipleValues();
    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     * @return The rssiMultipleValues.
     */
    com.google.protobuf.ByteString getRssiMultipleValues();

    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     * @return Whether the rssi field is set.
     */
    @java.lang.Deprecated boolean hasRssi();
    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     * @return The rssi.
     */
    @java.lang.Deprecated int getRssi();

    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @return A list containing the aemMultipleValues.
     */
    java.util.List<com.google.protobuf.ByteString> getAemMultipleValuesList();
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @return The count of aemMultipleValues.
     */
    int getAemMultipleValuesCount();
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @param index The index of the element to return.
     * @return The aemMultipleValues at the given index.
     */
    com.google.protobuf.ByteString getAemMultipleValues(int index);

    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     * @return Whether the aem field is set.
     */
    @java.lang.Deprecated boolean hasAem();
    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     * @return The aem.
     */
    @java.lang.Deprecated com.google.protobuf.ByteString getAem();

    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     * @return Whether the previousScanTimestamp field is set.
     */
    boolean hasPreviousScanTimestamp();
    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     * @return The previousScanTimestamp.
     */
    int getPreviousScanTimestamp();

    /**
     * <code>optional double latitude = 7;</code>
     * @return Whether the latitude field is set.
     */
    boolean hasLatitude();
    /**
     * <code>optional double latitude = 7;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>optional double longitude = 8;</code>
     * @return Whether the longitude field is set.
     */
    boolean hasLongitude();
    /**
     * <code>optional double longitude = 8;</code>
     * @return The longitude.
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code gmsreadout.ScanRecord}
   */
  public static final class ScanRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gmsreadout.ScanRecord)
      ScanRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScanRecord.newBuilder() to construct.
    private ScanRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScanRecord() {
      rssiMultipleValues_ = com.google.protobuf.ByteString.EMPTY;
      aemMultipleValues_ = java.util.Collections.emptyList();
      aem_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScanRecord();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScanRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              rssiMultipleValues_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rssi_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              aem_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              previousScanTimestamp_ = input.readUInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                aemMultipleValues_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000008;
              }
              aemMultipleValues_.add(input.readBytes());
              break;
            }
            case 57: {
              bitField0_ |= 0x00000020;
              latitude_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000040;
              longitude_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          aemMultipleValues_ = java.util.Collections.unmodifiableList(aemMultipleValues_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.class, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_;
    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public int getTimestamp() {
      return timestamp_;
    }

    public static final int RSSI_MULTIPLE_VALUES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString rssiMultipleValues_;
    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     * @return Whether the rssiMultipleValues field is set.
     */
    @java.lang.Override
    public boolean hasRssiMultipleValues() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     * @return The rssiMultipleValues.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRssiMultipleValues() {
      return rssiMultipleValues_;
    }

    public static final int RSSI_FIELD_NUMBER = 3;
    private int rssi_;
    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     * @return Whether the rssi field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasRssi() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     * @return The rssi.
     */
    @java.lang.Override
    @java.lang.Deprecated public int getRssi() {
      return rssi_;
    }

    public static final int AEM_MULTIPLE_VALUES_FIELD_NUMBER = 6;
    private java.util.List<com.google.protobuf.ByteString> aemMultipleValues_;
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @return A list containing the aemMultipleValues.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getAemMultipleValuesList() {
      return aemMultipleValues_;
    }
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @return The count of aemMultipleValues.
     */
    public int getAemMultipleValuesCount() {
      return aemMultipleValues_.size();
    }
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @param index The index of the element to return.
     * @return The aemMultipleValues at the given index.
     */
    public com.google.protobuf.ByteString getAemMultipleValues(int index) {
      return aemMultipleValues_.get(index);
    }

    public static final int AEM_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString aem_;
    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     * @return Whether the aem field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasAem() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     * @return The aem.
     */
    @java.lang.Override
    @java.lang.Deprecated public com.google.protobuf.ByteString getAem() {
      return aem_;
    }

    public static final int PREVIOUS_SCAN_TIMESTAMP_FIELD_NUMBER = 5;
    private int previousScanTimestamp_;
    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     * @return Whether the previousScanTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasPreviousScanTimestamp() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     * @return The previousScanTimestamp.
     */
    @java.lang.Override
    public int getPreviousScanTimestamp() {
      return previousScanTimestamp_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 7;
    private double latitude_;
    /**
     * <code>optional double latitude = 7;</code>
     * @return Whether the latitude field is set.
     */
    @java.lang.Override
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional double latitude = 7;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 8;
    private double longitude_;
    /**
     * <code>optional double longitude = 8;</code>
     * @return Whether the longitude field is set.
     */
    @java.lang.Override
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional double longitude = 8;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, rssiMultipleValues_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, rssi_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, aem_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt32(5, previousScanTimestamp_);
      }
      for (int i = 0; i < aemMultipleValues_.size(); i++) {
        output.writeBytes(6, aemMultipleValues_.get(i));
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeDouble(7, latitude_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeDouble(8, longitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, rssiMultipleValues_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rssi_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, aem_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, previousScanTimestamp_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < aemMultipleValues_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(aemMultipleValues_.get(i));
        }
        size += dataSize;
        size += 1 * getAemMultipleValuesList().size();
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, latitude_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, longitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord)) {
        return super.equals(obj);
      }
      org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord other = (org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord) obj;

      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (hasRssiMultipleValues() != other.hasRssiMultipleValues()) return false;
      if (hasRssiMultipleValues()) {
        if (!getRssiMultipleValues()
            .equals(other.getRssiMultipleValues())) return false;
      }
      if (hasRssi() != other.hasRssi()) return false;
      if (hasRssi()) {
        if (getRssi()
            != other.getRssi()) return false;
      }
      if (!getAemMultipleValuesList()
          .equals(other.getAemMultipleValuesList())) return false;
      if (hasAem() != other.hasAem()) return false;
      if (hasAem()) {
        if (!getAem()
            .equals(other.getAem())) return false;
      }
      if (hasPreviousScanTimestamp() != other.hasPreviousScanTimestamp()) return false;
      if (hasPreviousScanTimestamp()) {
        if (getPreviousScanTimestamp()
            != other.getPreviousScanTimestamp()) return false;
      }
      if (hasLatitude() != other.hasLatitude()) return false;
      if (hasLatitude()) {
        if (java.lang.Double.doubleToLongBits(getLatitude())
            != java.lang.Double.doubleToLongBits(
                other.getLatitude())) return false;
      }
      if (hasLongitude() != other.hasLongitude()) return false;
      if (hasLongitude()) {
        if (java.lang.Double.doubleToLongBits(getLongitude())
            != java.lang.Double.doubleToLongBits(
                other.getLongitude())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp();
      }
      if (hasRssiMultipleValues()) {
        hash = (37 * hash) + RSSI_MULTIPLE_VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getRssiMultipleValues().hashCode();
      }
      if (hasRssi()) {
        hash = (37 * hash) + RSSI_FIELD_NUMBER;
        hash = (53 * hash) + getRssi();
      }
      if (getAemMultipleValuesCount() > 0) {
        hash = (37 * hash) + AEM_MULTIPLE_VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getAemMultipleValuesList().hashCode();
      }
      if (hasAem()) {
        hash = (37 * hash) + AEM_FIELD_NUMBER;
        hash = (53 * hash) + getAem().hashCode();
      }
      if (hasPreviousScanTimestamp()) {
        hash = (37 * hash) + PREVIOUS_SCAN_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getPreviousScanTimestamp();
      }
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatitude()));
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gmsreadout.ScanRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gmsreadout.ScanRecord)
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.class, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder.class);
      }

      // Construct using org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rssiMultipleValues_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        rssi_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        aemMultipleValues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        aem_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        previousScanTimestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_descriptor;
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getDefaultInstanceForType() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance();
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord build() {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord buildPartial() {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord result = new org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rssiMultipleValues_ = rssiMultipleValues_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.rssi_ = rssi_;
          to_bitField0_ |= 0x00000004;
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          aemMultipleValues_ = java.util.Collections.unmodifiableList(aemMultipleValues_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.aemMultipleValues_ = aemMultipleValues_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.aem_ = aem_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.previousScanTimestamp_ = previousScanTimestamp_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.latitude_ = latitude_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.longitude_ = longitude_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord) {
          return mergeFrom((org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord other) {
        if (other == org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasRssiMultipleValues()) {
          setRssiMultipleValues(other.getRssiMultipleValues());
        }
        if (other.hasRssi()) {
          setRssi(other.getRssi());
        }
        if (!other.aemMultipleValues_.isEmpty()) {
          if (aemMultipleValues_.isEmpty()) {
            aemMultipleValues_ = other.aemMultipleValues_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureAemMultipleValuesIsMutable();
            aemMultipleValues_.addAll(other.aemMultipleValues_);
          }
          onChanged();
        }
        if (other.hasAem()) {
          setAem(other.getAem());
        }
        if (other.hasPreviousScanTimestamp()) {
          setPreviousScanTimestamp(other.getPreviousScanTimestamp());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int timestamp_ ;
      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rssiMultipleValues_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       * @return Whether the rssiMultipleValues field is set.
       */
      @java.lang.Override
      public boolean hasRssiMultipleValues() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       * @return The rssiMultipleValues.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRssiMultipleValues() {
        return rssiMultipleValues_;
      }
      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       * @param value The rssiMultipleValues to set.
       * @return This builder for chaining.
       */
      public Builder setRssiMultipleValues(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        rssiMultipleValues_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRssiMultipleValues() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rssiMultipleValues_ = getDefaultInstance().getRssiMultipleValues();
        onChanged();
        return this;
      }

      private int rssi_ ;
      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       * @return Whether the rssi field is set.
       */
      @java.lang.Override
      @java.lang.Deprecated public boolean hasRssi() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       * @return The rssi.
       */
      @java.lang.Override
      @java.lang.Deprecated public int getRssi() {
        return rssi_;
      }
      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       * @param value The rssi to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setRssi(int value) {
        bitField0_ |= 0x00000004;
        rssi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearRssi() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rssi_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> aemMultipleValues_ = java.util.Collections.emptyList();
      private void ensureAemMultipleValuesIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          aemMultipleValues_ = new java.util.ArrayList<com.google.protobuf.ByteString>(aemMultipleValues_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @return A list containing the aemMultipleValues.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getAemMultipleValuesList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(aemMultipleValues_) : aemMultipleValues_;
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @return The count of aemMultipleValues.
       */
      public int getAemMultipleValuesCount() {
        return aemMultipleValues_.size();
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @param index The index of the element to return.
       * @return The aemMultipleValues at the given index.
       */
      public com.google.protobuf.ByteString getAemMultipleValues(int index) {
        return aemMultipleValues_.get(index);
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @param index The index to set the value at.
       * @param value The aemMultipleValues to set.
       * @return This builder for chaining.
       */
      public Builder setAemMultipleValues(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAemMultipleValuesIsMutable();
        aemMultipleValues_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @param value The aemMultipleValues to add.
       * @return This builder for chaining.
       */
      public Builder addAemMultipleValues(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAemMultipleValuesIsMutable();
        aemMultipleValues_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @param values The aemMultipleValues to add.
       * @return This builder for chaining.
       */
      public Builder addAllAemMultipleValues(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureAemMultipleValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aemMultipleValues_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAemMultipleValues() {
        aemMultipleValues_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString aem_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       * @return Whether the aem field is set.
       */
      @java.lang.Override
      @java.lang.Deprecated public boolean hasAem() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       * @return The aem.
       */
      @java.lang.Override
      @java.lang.Deprecated public com.google.protobuf.ByteString getAem() {
        return aem_;
      }
      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       * @param value The aem to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setAem(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        aem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearAem() {
        bitField0_ = (bitField0_ & ~0x00000010);
        aem_ = getDefaultInstance().getAem();
        onChanged();
        return this;
      }

      private int previousScanTimestamp_ ;
      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       * @return Whether the previousScanTimestamp field is set.
       */
      @java.lang.Override
      public boolean hasPreviousScanTimestamp() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       * @return The previousScanTimestamp.
       */
      @java.lang.Override
      public int getPreviousScanTimestamp() {
        return previousScanTimestamp_;
      }
      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       * @param value The previousScanTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setPreviousScanTimestamp(int value) {
        bitField0_ |= 0x00000020;
        previousScanTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreviousScanTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        previousScanTimestamp_ = 0;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>optional double latitude = 7;</code>
       * @return Whether the latitude field is set.
       */
      @java.lang.Override
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional double latitude = 7;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>optional double latitude = 7;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000040;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double latitude = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000040);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>optional double longitude = 8;</code>
       * @return Whether the longitude field is set.
       */
      @java.lang.Override
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional double longitude = 8;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional double longitude = 8;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000080;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double longitude = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000080);
        longitude_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gmsreadout.ScanRecord)
    }

    // @@protoc_insertion_point(class_scope:gmsreadout.ScanRecord)
    private static final org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord();
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ScanRecord>
        PARSER = new com.google.protobuf.AbstractParser<ScanRecord>() {
      @java.lang.Override
      public ScanRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScanRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScanRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScanRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContactRecordsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gmsreadout.ContactRecords)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> 
        getRecordList();
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index);
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    int getRecordCount();
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    java.util.List<? extends org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
        getRecordOrBuilderList();
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder getRecordOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gmsreadout.ContactRecords}
   */
  public static final class ContactRecords extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gmsreadout.ContactRecords)
      ContactRecordsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContactRecords.newBuilder() to construct.
    private ContactRecords(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContactRecords() {
      record_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContactRecords();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContactRecords(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                record_ = new java.util.ArrayList<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord>();
                mutable_bitField0_ |= 0x00000001;
              }
              record_.add(
                  input.readMessage(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          record_ = java.util.Collections.unmodifiableList(record_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.class, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.Builder.class);
    }

    public static final int RECORD_FIELD_NUMBER = 1;
    private java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> record_;
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> getRecordList() {
      return record_;
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
        getRecordOrBuilderList() {
      return record_;
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public int getRecordCount() {
      return record_.size();
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index) {
      return record_.get(index);
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder getRecordOrBuilder(
        int index) {
      return record_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < record_.size(); i++) {
        output.writeMessage(1, record_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < record_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, record_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords)) {
        return super.equals(obj);
      }
      org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords other = (org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords) obj;

      if (!getRecordList()
          .equals(other.getRecordList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRecordCount() > 0) {
        hash = (37 * hash) + RECORD_FIELD_NUMBER;
        hash = (53 * hash) + getRecordList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gmsreadout.ContactRecords}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gmsreadout.ContactRecords)
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecordsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.class, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.Builder.class);
      }

      // Construct using org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRecordFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (recordBuilder_ == null) {
          record_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          recordBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_descriptor;
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords getDefaultInstanceForType() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.getDefaultInstance();
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords build() {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords buildPartial() {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords result = new org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords(this);
        int from_bitField0_ = bitField0_;
        if (recordBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            record_ = java.util.Collections.unmodifiableList(record_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.record_ = record_;
        } else {
          result.record_ = recordBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords) {
          return mergeFrom((org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords other) {
        if (other == org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.getDefaultInstance()) return this;
        if (recordBuilder_ == null) {
          if (!other.record_.isEmpty()) {
            if (record_.isEmpty()) {
              record_ = other.record_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRecordIsMutable();
              record_.addAll(other.record_);
            }
            onChanged();
          }
        } else {
          if (!other.record_.isEmpty()) {
            if (recordBuilder_.isEmpty()) {
              recordBuilder_.dispose();
              recordBuilder_ = null;
              record_ = other.record_;
              bitField0_ = (bitField0_ & ~0x00000001);
              recordBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecordFieldBuilder() : null;
            } else {
              recordBuilder_.addAllMessages(other.record_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> record_ =
        java.util.Collections.emptyList();
      private void ensureRecordIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          record_ = new java.util.ArrayList<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord>(record_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> recordBuilder_;

      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> getRecordList() {
        if (recordBuilder_ == null) {
          return java.util.Collections.unmodifiableList(record_);
        } else {
          return recordBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public int getRecordCount() {
        if (recordBuilder_ == null) {
          return record_.size();
        } else {
          return recordBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index) {
        if (recordBuilder_ == null) {
          return record_.get(index);
        } else {
          return recordBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder setRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.set(index, value);
          onChanged();
        } else {
          recordBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder setRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.set(index, builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.add(value);
          onChanged();
        } else {
          recordBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.add(index, value);
          onChanged();
        } else {
          recordBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.add(builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.add(index, builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addAllRecord(
          java.lang.Iterable<? extends org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> values) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, record_);
          onChanged();
        } else {
          recordBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder clearRecord() {
        if (recordBuilder_ == null) {
          record_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          recordBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder removeRecord(int index) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.remove(index);
          onChanged();
        } else {
          recordBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder getRecordBuilder(
          int index) {
        return getRecordFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder getRecordOrBuilder(
          int index) {
        if (recordBuilder_ == null) {
          return record_.get(index);  } else {
          return recordBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public java.util.List<? extends org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
           getRecordOrBuilderList() {
        if (recordBuilder_ != null) {
          return recordBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(record_);
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder addRecordBuilder() {
        return getRecordFieldBuilder().addBuilder(
            org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder addRecordBuilder(
          int index) {
        return getRecordFieldBuilder().addBuilder(
            index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder> 
           getRecordBuilderList() {
        return getRecordFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
          getRecordFieldBuilder() {
        if (recordBuilder_ == null) {
          recordBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder>(
                  record_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          record_ = null;
        }
        return recordBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gmsreadout.ContactRecords)
    }

    // @@protoc_insertion_point(class_scope:gmsreadout.ContactRecords)
    private static final org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords();
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ContactRecords>
        PARSER = new com.google.protobuf.AbstractParser<ContactRecords>() {
      @java.lang.Override
      public ContactRecords parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactRecords(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContactRecords> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContactRecords> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gmsreadout_ScanRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gmsreadout_ScanRecord_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gmsreadout_ContactRecords_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gmsreadout_ContactRecords_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n`corona-warn-companion/src/main/java/or" +
      "g/tosl/coronawarncompanion/gmsreadout/Co" +
      "ntactRecords.proto\022\ngmsreadout\"\303\001\n\nScanR" +
      "ecord\022\021\n\ttimestamp\030\001 \001(\r\022\034\n\024rssi_multipl" +
      "e_values\030\002 \001(\014\022\020\n\004rssi\030\003 \001(\005B\002\030\001\022\033\n\023aem_" +
      "multiple_values\030\006 \003(\014\022\017\n\003aem\030\004 \001(\014B\002\030\001\022\037" +
      "\n\027previous_scan_timestamp\030\005 \001(\r\022\020\n\010latit" +
      "ude\030\007 \001(\001\022\021\n\tlongitude\030\010 \001(\001\"8\n\016ContactR" +
      "ecords\022&\n\006record\030\001 \003(\0132\026.gmsreadout.Scan" +
      "RecordB?\n\'org.tosl.coronawarncompanion.g" +
      "msreadoutB\024ContactRecordsProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gmsreadout_ScanRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gmsreadout_ScanRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gmsreadout_ScanRecord_descriptor,
        new java.lang.String[] { "Timestamp", "RssiMultipleValues", "Rssi", "AemMultipleValues", "Aem", "PreviousScanTimestamp", "Latitude", "Longitude", });
    internal_static_gmsreadout_ContactRecords_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gmsreadout_ContactRecords_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gmsreadout_ContactRecords_descriptor,
        new java.lang.String[] { "Record", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
