// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/tosl/coronawarncompanion/gmsreadout/ContactRecords.proto

package org.tosl.coronawarncompanion.gmsreadout;

public final class ContactRecordsProtos {
  private ContactRecordsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ScanRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gmsreadout.ScanRecord)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    int getTimestamp();

    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     * @return Whether the rssiMultipleValues field is set.
     */
    boolean hasRssiMultipleValues();
    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     * @return The rssiMultipleValues.
     */
    com.google.protobuf.ByteString getRssiMultipleValues();

    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     * @return Whether the rssi field is set.
     */
    @java.lang.Deprecated boolean hasRssi();
    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     * @return The rssi.
     */
    @java.lang.Deprecated int getRssi();

    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @return A list containing the aemMultipleValues.
     */
    java.util.List<com.google.protobuf.ByteString> getAemMultipleValuesList();
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @return The count of aemMultipleValues.
     */
    int getAemMultipleValuesCount();
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @param index The index of the element to return.
     * @return The aemMultipleValues at the given index.
     */
    com.google.protobuf.ByteString getAemMultipleValues(int index);

    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     * @return Whether the aem field is set.
     */
    @java.lang.Deprecated boolean hasAem();
    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     * @return The aem.
     */
    @java.lang.Deprecated com.google.protobuf.ByteString getAem();

    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     * @return Whether the previousScanTimestamp field is set.
     */
    boolean hasPreviousScanTimestamp();
    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     * @return The previousScanTimestamp.
     */
    int getPreviousScanTimestamp();

    /**
     * <pre>
     * latitude / longitude are not part of the GMS database, they are only
     * </pre>
     *
     * <code>optional double latitude = 7;</code>
     * @return Whether the latitude field is set.
     */
    boolean hasLatitude();
    /**
     * <pre>
     * latitude / longitude are not part of the GMS database, they are only
     * </pre>
     *
     * <code>optional double latitude = 7;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <pre>
     * added here because this protobuf format is used in all modes.
     * </pre>
     *
     * <code>optional double longitude = 8;</code>
     * @return Whether the longitude field is set.
     */
    boolean hasLongitude();
    /**
     * <pre>
     * added here because this protobuf format is used in all modes.
     * </pre>
     *
     * <code>optional double longitude = 8;</code>
     * @return The longitude.
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code gmsreadout.ScanRecord}
   */
  public  static final class ScanRecord extends
      com.google.protobuf.GeneratedMessageLite<
          ScanRecord, ScanRecord.Builder> implements
      // @@protoc_insertion_point(message_implements:gmsreadout.ScanRecord)
      ScanRecordOrBuilder {
    private ScanRecord() {
      rssiMultipleValues_ = com.google.protobuf.ByteString.EMPTY;
      aemMultipleValues_ = emptyProtobufList();
      aem_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_;
    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public int getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(int value) {
      bitField0_ |= 0x00000001;
      timestamp_ = value;
    }
    /**
     * <code>optional uint32 timestamp = 1;</code>
     */
    private void clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestamp_ = 0;
    }

    public static final int RSSI_MULTIPLE_VALUES_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString rssiMultipleValues_;
    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     * @return Whether the rssiMultipleValues field is set.
     */
    @java.lang.Override
    public boolean hasRssiMultipleValues() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     * @return The rssiMultipleValues.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRssiMultipleValues() {
      return rssiMultipleValues_;
    }
    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     * @param value The rssiMultipleValues to set.
     */
    private void setRssiMultipleValues(com.google.protobuf.ByteString value) {
      value.getClass();
  bitField0_ |= 0x00000002;
      rssiMultipleValues_ = value;
    }
    /**
     * <code>optional bytes rssi_multiple_values = 2;</code>
     */
    private void clearRssiMultipleValues() {
      bitField0_ = (bitField0_ & ~0x00000002);
      rssiMultipleValues_ = getDefaultInstance().getRssiMultipleValues();
    }

    public static final int RSSI_FIELD_NUMBER = 3;
    private int rssi_;
    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     * @return Whether the rssi field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasRssi() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     * @return The rssi.
     */
    @java.lang.Override
    @java.lang.Deprecated public int getRssi() {
      return rssi_;
    }
    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     * @param value The rssi to set.
     */
    private void setRssi(int value) {
      bitField0_ |= 0x00000004;
      rssi_ = value;
    }
    /**
     * <code>optional int32 rssi = 3 [deprecated = true];</code>
     */
    private void clearRssi() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rssi_ = 0;
    }

    public static final int AEM_MULTIPLE_VALUES_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> aemMultipleValues_;
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @return A list containing the aemMultipleValues.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getAemMultipleValuesList() {
      return aemMultipleValues_;
    }
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @return The count of aemMultipleValues.
     */
    @java.lang.Override
    public int getAemMultipleValuesCount() {
      return aemMultipleValues_.size();
    }
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @param index The index of the element to return.
     * @return The aemMultipleValues at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAemMultipleValues(int index) {
      return aemMultipleValues_.get(index);
    }
    private void ensureAemMultipleValuesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> tmp = aemMultipleValues_;
      if (!tmp.isModifiable()) {
        aemMultipleValues_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @param index The index to set the value at.
     * @param value The aemMultipleValues to set.
     */
    private void setAemMultipleValues(
        int index, com.google.protobuf.ByteString value) {
      value.getClass();
  ensureAemMultipleValuesIsMutable();
      aemMultipleValues_.set(index, value);
    }
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @param value The aemMultipleValues to add.
     */
    private void addAemMultipleValues(com.google.protobuf.ByteString value) {
      value.getClass();
  ensureAemMultipleValuesIsMutable();
      aemMultipleValues_.add(value);
    }
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     * @param values The aemMultipleValues to add.
     */
    private void addAllAemMultipleValues(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureAemMultipleValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, aemMultipleValues_);
    }
    /**
     * <code>repeated bytes aem_multiple_values = 6;</code>
     */
    private void clearAemMultipleValues() {
      aemMultipleValues_ = emptyProtobufList();
    }

    public static final int AEM_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString aem_;
    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     * @return Whether the aem field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasAem() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     * @return The aem.
     */
    @java.lang.Override
    @java.lang.Deprecated public com.google.protobuf.ByteString getAem() {
      return aem_;
    }
    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     * @param value The aem to set.
     */
    private void setAem(com.google.protobuf.ByteString value) {
      value.getClass();
  bitField0_ |= 0x00000008;
      aem_ = value;
    }
    /**
     * <code>optional bytes aem = 4 [deprecated = true];</code>
     */
    private void clearAem() {
      bitField0_ = (bitField0_ & ~0x00000008);
      aem_ = getDefaultInstance().getAem();
    }

    public static final int PREVIOUS_SCAN_TIMESTAMP_FIELD_NUMBER = 5;
    private int previousScanTimestamp_;
    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     * @return Whether the previousScanTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasPreviousScanTimestamp() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     * @return The previousScanTimestamp.
     */
    @java.lang.Override
    public int getPreviousScanTimestamp() {
      return previousScanTimestamp_;
    }
    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     * @param value The previousScanTimestamp to set.
     */
    private void setPreviousScanTimestamp(int value) {
      bitField0_ |= 0x00000010;
      previousScanTimestamp_ = value;
    }
    /**
     * <code>optional uint32 previous_scan_timestamp = 5;</code>
     */
    private void clearPreviousScanTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000010);
      previousScanTimestamp_ = 0;
    }

    public static final int LATITUDE_FIELD_NUMBER = 7;
    private double latitude_;
    /**
     * <pre>
     * latitude / longitude are not part of the GMS database, they are only
     * </pre>
     *
     * <code>optional double latitude = 7;</code>
     * @return Whether the latitude field is set.
     */
    @java.lang.Override
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * latitude / longitude are not part of the GMS database, they are only
     * </pre>
     *
     * <code>optional double latitude = 7;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }
    /**
     * <pre>
     * latitude / longitude are not part of the GMS database, they are only
     * </pre>
     *
     * <code>optional double latitude = 7;</code>
     * @param value The latitude to set.
     */
    private void setLatitude(double value) {
      bitField0_ |= 0x00000020;
      latitude_ = value;
    }
    /**
     * <pre>
     * latitude / longitude are not part of the GMS database, they are only
     * </pre>
     *
     * <code>optional double latitude = 7;</code>
     */
    private void clearLatitude() {
      bitField0_ = (bitField0_ & ~0x00000020);
      latitude_ = 0D;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 8;
    private double longitude_;
    /**
     * <pre>
     * added here because this protobuf format is used in all modes.
     * </pre>
     *
     * <code>optional double longitude = 8;</code>
     * @return Whether the longitude field is set.
     */
    @java.lang.Override
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * added here because this protobuf format is used in all modes.
     * </pre>
     *
     * <code>optional double longitude = 8;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }
    /**
     * <pre>
     * added here because this protobuf format is used in all modes.
     * </pre>
     *
     * <code>optional double longitude = 8;</code>
     * @param value The longitude to set.
     */
    private void setLongitude(double value) {
      bitField0_ |= 0x00000040;
      longitude_ = value;
    }
    /**
     * <pre>
     * added here because this protobuf format is used in all modes.
     * </pre>
     *
     * <code>optional double longitude = 8;</code>
     */
    private void clearLongitude() {
      bitField0_ = (bitField0_ & ~0x00000040);
      longitude_ = 0D;
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gmsreadout.ScanRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord, Builder> implements
        // @@protoc_insertion_point(builder_implements:gmsreadout.ScanRecord)
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder {
      // Construct using org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return instance.hasTimestamp();
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public int getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(int value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       * @return Whether the rssiMultipleValues field is set.
       */
      @java.lang.Override
      public boolean hasRssiMultipleValues() {
        return instance.hasRssiMultipleValues();
      }
      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       * @return The rssiMultipleValues.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRssiMultipleValues() {
        return instance.getRssiMultipleValues();
      }
      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       * @param value The rssiMultipleValues to set.
       * @return This builder for chaining.
       */
      public Builder setRssiMultipleValues(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRssiMultipleValues(value);
        return this;
      }
      /**
       * <code>optional bytes rssi_multiple_values = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRssiMultipleValues() {
        copyOnWrite();
        instance.clearRssiMultipleValues();
        return this;
      }

      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       * @return Whether the rssi field is set.
       */
      @java.lang.Override
      @java.lang.Deprecated public boolean hasRssi() {
        return instance.hasRssi();
      }
      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       * @return The rssi.
       */
      @java.lang.Override
      @java.lang.Deprecated public int getRssi() {
        return instance.getRssi();
      }
      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       * @param value The rssi to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setRssi(int value) {
        copyOnWrite();
        instance.setRssi(value);
        return this;
      }
      /**
       * <code>optional int32 rssi = 3 [deprecated = true];</code>
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearRssi() {
        copyOnWrite();
        instance.clearRssi();
        return this;
      }

      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @return A list containing the aemMultipleValues.
       */
      @java.lang.Override
      public java.util.List<com.google.protobuf.ByteString>
          getAemMultipleValuesList() {
        return java.util.Collections.unmodifiableList(
            instance.getAemMultipleValuesList());
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @return The count of aemMultipleValues.
       */
      @java.lang.Override
      public int getAemMultipleValuesCount() {
        return instance.getAemMultipleValuesCount();
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @param index The index of the element to return.
       * @return The aemMultipleValues at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAemMultipleValues(int index) {
        return instance.getAemMultipleValues(index);
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @param value The aemMultipleValues to set.
       * @return This builder for chaining.
       */
      public Builder setAemMultipleValues(
          int index, com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAemMultipleValues(index, value);
        return this;
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @param value The aemMultipleValues to add.
       * @return This builder for chaining.
       */
      public Builder addAemMultipleValues(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addAemMultipleValues(value);
        return this;
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @param values The aemMultipleValues to add.
       * @return This builder for chaining.
       */
      public Builder addAllAemMultipleValues(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        copyOnWrite();
        instance.addAllAemMultipleValues(values);
        return this;
      }
      /**
       * <code>repeated bytes aem_multiple_values = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAemMultipleValues() {
        copyOnWrite();
        instance.clearAemMultipleValues();
        return this;
      }

      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       * @return Whether the aem field is set.
       */
      @java.lang.Override
      @java.lang.Deprecated public boolean hasAem() {
        return instance.hasAem();
      }
      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       * @return The aem.
       */
      @java.lang.Override
      @java.lang.Deprecated public com.google.protobuf.ByteString getAem() {
        return instance.getAem();
      }
      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       * @param value The aem to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setAem(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAem(value);
        return this;
      }
      /**
       * <code>optional bytes aem = 4 [deprecated = true];</code>
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearAem() {
        copyOnWrite();
        instance.clearAem();
        return this;
      }

      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       * @return Whether the previousScanTimestamp field is set.
       */
      @java.lang.Override
      public boolean hasPreviousScanTimestamp() {
        return instance.hasPreviousScanTimestamp();
      }
      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       * @return The previousScanTimestamp.
       */
      @java.lang.Override
      public int getPreviousScanTimestamp() {
        return instance.getPreviousScanTimestamp();
      }
      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       * @param value The previousScanTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setPreviousScanTimestamp(int value) {
        copyOnWrite();
        instance.setPreviousScanTimestamp(value);
        return this;
      }
      /**
       * <code>optional uint32 previous_scan_timestamp = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreviousScanTimestamp() {
        copyOnWrite();
        instance.clearPreviousScanTimestamp();
        return this;
      }

      /**
       * <pre>
       * latitude / longitude are not part of the GMS database, they are only
       * </pre>
       *
       * <code>optional double latitude = 7;</code>
       * @return Whether the latitude field is set.
       */
      @java.lang.Override
      public boolean hasLatitude() {
        return instance.hasLatitude();
      }
      /**
       * <pre>
       * latitude / longitude are not part of the GMS database, they are only
       * </pre>
       *
       * <code>optional double latitude = 7;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return instance.getLatitude();
      }
      /**
       * <pre>
       * latitude / longitude are not part of the GMS database, they are only
       * </pre>
       *
       * <code>optional double latitude = 7;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        copyOnWrite();
        instance.setLatitude(value);
        return this;
      }
      /**
       * <pre>
       * latitude / longitude are not part of the GMS database, they are only
       * </pre>
       *
       * <code>optional double latitude = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        copyOnWrite();
        instance.clearLatitude();
        return this;
      }

      /**
       * <pre>
       * added here because this protobuf format is used in all modes.
       * </pre>
       *
       * <code>optional double longitude = 8;</code>
       * @return Whether the longitude field is set.
       */
      @java.lang.Override
      public boolean hasLongitude() {
        return instance.hasLongitude();
      }
      /**
       * <pre>
       * added here because this protobuf format is used in all modes.
       * </pre>
       *
       * <code>optional double longitude = 8;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return instance.getLongitude();
      }
      /**
       * <pre>
       * added here because this protobuf format is used in all modes.
       * </pre>
       *
       * <code>optional double longitude = 8;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        copyOnWrite();
        instance.setLongitude(value);
        return this;
      }
      /**
       * <pre>
       * added here because this protobuf format is used in all modes.
       * </pre>
       *
       * <code>optional double longitude = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        copyOnWrite();
        instance.clearLongitude();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gmsreadout.ScanRecord)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "timestamp_",
              "rssiMultipleValues_",
              "rssi_",
              "aem_",
              "previousScanTimestamp_",
              "aemMultipleValues_",
              "latitude_",
              "longitude_",
            };
            java.lang.String info =
                "\u0001\b\u0000\u0001\u0001\b\b\u0000\u0001\u0000\u0001\u100b\u0000\u0002\u100a\u0001" +
                "\u0003\u1004\u0002\u0004\u100a\u0003\u0005\u100b\u0004\u0006\u001c\u0007\u1000\u0005" +
                "\b\u1000\u0006";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> parser = PARSER;
          if (parser == null) {
            synchronized (org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gmsreadout.ScanRecord)
    private static final org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord DEFAULT_INSTANCE;
    static {
      ScanRecord defaultInstance = new ScanRecord();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ScanRecord.class, defaultInstance);
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ScanRecord> PARSER;

    public static com.google.protobuf.Parser<ScanRecord> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ContactRecordsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gmsreadout.ContactRecords)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> 
        getRecordList();
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index);
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    int getRecordCount();
  }
  /**
   * Protobuf type {@code gmsreadout.ContactRecords}
   */
  public  static final class ContactRecords extends
      com.google.protobuf.GeneratedMessageLite<
          ContactRecords, ContactRecords.Builder> implements
      // @@protoc_insertion_point(message_implements:gmsreadout.ContactRecords)
      ContactRecordsOrBuilder {
    private ContactRecords() {
      record_ = emptyProtobufList();
    }
    public static final int RECORD_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> record_;
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> getRecordList() {
      return record_;
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    public java.util.List<? extends org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
        getRecordOrBuilderList() {
      return record_;
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public int getRecordCount() {
      return record_.size();
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index) {
      return record_.get(index);
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder getRecordOrBuilder(
        int index) {
      return record_.get(index);
    }
    private void ensureRecordIsMutable() {
      com.google.protobuf.Internal.ProtobufList<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> tmp = record_;
      if (!tmp.isModifiable()) {
        record_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    private void setRecord(
        int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
      value.getClass();
  ensureRecordIsMutable();
      record_.set(index, value);
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    private void addRecord(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
      value.getClass();
  ensureRecordIsMutable();
      record_.add(value);
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    private void addRecord(
        int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
      value.getClass();
  ensureRecordIsMutable();
      record_.add(index, value);
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    private void addAllRecord(
        java.lang.Iterable<? extends org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> values) {
      ensureRecordIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, record_);
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    private void clearRecord() {
      record_ = emptyProtobufList();
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    private void removeRecord(int index) {
      ensureRecordIsMutable();
      record_.remove(index);
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gmsreadout.ContactRecords}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords, Builder> implements
        // @@protoc_insertion_point(builder_implements:gmsreadout.ContactRecords)
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecordsOrBuilder {
      // Construct using org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      @java.lang.Override
      public java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> getRecordList() {
        return java.util.Collections.unmodifiableList(
            instance.getRecordList());
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      @java.lang.Override
      public int getRecordCount() {
        return instance.getRecordCount();
      }/**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index) {
        return instance.getRecord(index);
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder setRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        copyOnWrite();
        instance.setRecord(index, value);
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder setRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        copyOnWrite();
        instance.setRecord(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        copyOnWrite();
        instance.addRecord(value);
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        copyOnWrite();
        instance.addRecord(index, value);
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        copyOnWrite();
        instance.addRecord(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        copyOnWrite();
        instance.addRecord(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addAllRecord(
          java.lang.Iterable<? extends org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> values) {
        copyOnWrite();
        instance.addAllRecord(values);
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder clearRecord() {
        copyOnWrite();
        instance.clearRecord();
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder removeRecord(int index) {
        copyOnWrite();
        instance.removeRecord(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gmsreadout.ContactRecords)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "record_",
              org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.class,
            };
            java.lang.String info =
                "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords> parser = PARSER;
          if (parser == null) {
            synchronized (org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gmsreadout.ContactRecords)
    private static final org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords DEFAULT_INSTANCE;
    static {
      ContactRecords defaultInstance = new ContactRecords();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ContactRecords.class, defaultInstance);
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ContactRecords> PARSER;

    public static com.google.protobuf.Parser<ContactRecords> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
