/*
 * Corona-Warn-Companion. An app that shows COVID-19 Exposure Notifications details.
 * Copyright (C) 2020  Michael Huebler <corona-warn-companion@tosl.org> and other contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContactRecords.proto

package org.tosl.coronawarncompanion.gmsreadout;

@SuppressWarnings("ALL")
public final class ContactRecordsProtos {
  private ContactRecordsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScanRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gmsreadout.ScanRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    int getTimestamp();

    /**
     * <code>optional int64 rssi = 3;</code>
     * @return Whether the rssi field is set.
     */
    boolean hasRssi();
    /**
     * <code>optional int64 rssi = 3;</code>
     * @return The rssi.
     */
    long getRssi();

    /**
     * <code>optional bytes aem = 4;</code>
     * @return Whether the aem field is set.
     */
    boolean hasAem();
    /**
     * <code>optional bytes aem = 4;</code>
     * @return The aem.
     */
    com.google.protobuf.ByteString getAem();
  }
  /**
   * Protobuf type {@code gmsreadout.ScanRecord}
   */
  public static final class ScanRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gmsreadout.ScanRecord)
      ScanRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScanRecord.newBuilder() to construct.
    private ScanRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScanRecord() {
      aem_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScanRecord();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScanRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              rssi_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              aem_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.class, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_;
    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public int getTimestamp() {
      return timestamp_;
    }

    public static final int RSSI_FIELD_NUMBER = 3;
    private long rssi_;
    /**
     * <code>optional int64 rssi = 3;</code>
     * @return Whether the rssi field is set.
     */
    @java.lang.Override
    public boolean hasRssi() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 rssi = 3;</code>
     * @return The rssi.
     */
    @java.lang.Override
    public long getRssi() {
      return rssi_;
    }

    public static final int AEM_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString aem_;
    /**
     * <code>optional bytes aem = 4;</code>
     * @return Whether the aem field is set.
     */
    @java.lang.Override
    public boolean hasAem() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes aem = 4;</code>
     * @return The aem.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAem() {
      return aem_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(3, rssi_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(4, aem_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, rssi_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, aem_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord)) {
        return super.equals(obj);
      }
      org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord other = (org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord) obj;

      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (hasRssi() != other.hasRssi()) return false;
      if (hasRssi()) {
        if (getRssi()
            != other.getRssi()) return false;
      }
      if (hasAem() != other.hasAem()) return false;
      if (hasAem()) {
        if (!getAem()
            .equals(other.getAem())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp();
      }
      if (hasRssi()) {
        hash = (37 * hash) + RSSI_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRssi());
      }
      if (hasAem()) {
        hash = (37 * hash) + AEM_FIELD_NUMBER;
        hash = (53 * hash) + getAem().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gmsreadout.ScanRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gmsreadout.ScanRecord)
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.class, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder.class);
      }

      // Construct using org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rssi_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        aem_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ScanRecord_descriptor;
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getDefaultInstanceForType() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance();
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord build() {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord buildPartial() {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord result = new org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.rssi_ = rssi_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.aem_ = aem_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord) {
          return mergeFrom((org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord other) {
        if (other == org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasRssi()) {
          setRssi(other.getRssi());
        }
        if (other.hasAem()) {
          setAem(other.getAem());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int timestamp_ ;
      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      private long rssi_ ;
      /**
       * <code>optional int64 rssi = 3;</code>
       * @return Whether the rssi field is set.
       */
      @java.lang.Override
      public boolean hasRssi() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int64 rssi = 3;</code>
       * @return The rssi.
       */
      @java.lang.Override
      public long getRssi() {
        return rssi_;
      }
      /**
       * <code>optional int64 rssi = 3;</code>
       * @param value The rssi to set.
       * @return This builder for chaining.
       */
      public Builder setRssi(long value) {
        bitField0_ |= 0x00000002;
        rssi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 rssi = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRssi() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rssi_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString aem_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes aem = 4;</code>
       * @return Whether the aem field is set.
       */
      @java.lang.Override
      public boolean hasAem() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes aem = 4;</code>
       * @return The aem.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAem() {
        return aem_;
      }
      /**
       * <code>optional bytes aem = 4;</code>
       * @param value The aem to set.
       * @return This builder for chaining.
       */
      public Builder setAem(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        aem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes aem = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAem() {
        bitField0_ = (bitField0_ & ~0x00000004);
        aem_ = getDefaultInstance().getAem();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gmsreadout.ScanRecord)
    }

    // @@protoc_insertion_point(class_scope:gmsreadout.ScanRecord)
    private static final org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord();
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ScanRecord>
        PARSER = new com.google.protobuf.AbstractParser<ScanRecord>() {
      @java.lang.Override
      public ScanRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScanRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScanRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScanRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContactRecordsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gmsreadout.ContactRecords)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> 
        getRecordList();
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index);
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    int getRecordCount();
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    java.util.List<? extends org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
        getRecordOrBuilderList();
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder getRecordOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gmsreadout.ContactRecords}
   */
  public static final class ContactRecords extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gmsreadout.ContactRecords)
      ContactRecordsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContactRecords.newBuilder() to construct.
    private ContactRecords(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContactRecords() {
      record_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContactRecords();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContactRecords(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                record_ = new java.util.ArrayList<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord>();
                mutable_bitField0_ |= 0x00000001;
              }
              record_.add(
                  input.readMessage(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          record_ = java.util.Collections.unmodifiableList(record_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.class, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.Builder.class);
    }

    public static final int RECORD_FIELD_NUMBER = 1;
    private java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> record_;
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> getRecordList() {
      return record_;
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
        getRecordOrBuilderList() {
      return record_;
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public int getRecordCount() {
      return record_.size();
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index) {
      return record_.get(index);
    }
    /**
     * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
     */
    @java.lang.Override
    public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder getRecordOrBuilder(
        int index) {
      return record_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < record_.size(); i++) {
        output.writeMessage(1, record_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < record_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, record_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords)) {
        return super.equals(obj);
      }
      org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords other = (org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords) obj;

      if (!getRecordList()
          .equals(other.getRecordList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRecordCount() > 0) {
        hash = (37 * hash) + RECORD_FIELD_NUMBER;
        hash = (53 * hash) + getRecordList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gmsreadout.ContactRecords}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gmsreadout.ContactRecords)
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecordsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.class, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.Builder.class);
      }

      // Construct using org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRecordFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (recordBuilder_ == null) {
          record_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          recordBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.internal_static_gmsreadout_ContactRecords_descriptor;
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords getDefaultInstanceForType() {
        return org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.getDefaultInstance();
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords build() {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords buildPartial() {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords result = new org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords(this);
        int from_bitField0_ = bitField0_;
        if (recordBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            record_ = java.util.Collections.unmodifiableList(record_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.record_ = record_;
        } else {
          result.record_ = recordBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords) {
          return mergeFrom((org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords other) {
        if (other == org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords.getDefaultInstance()) return this;
        if (recordBuilder_ == null) {
          if (!other.record_.isEmpty()) {
            if (record_.isEmpty()) {
              record_ = other.record_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRecordIsMutable();
              record_.addAll(other.record_);
            }
            onChanged();
          }
        } else {
          if (!other.record_.isEmpty()) {
            if (recordBuilder_.isEmpty()) {
              recordBuilder_.dispose();
              recordBuilder_ = null;
              record_ = other.record_;
              bitField0_ = (bitField0_ & ~0x00000001);
              recordBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecordFieldBuilder() : null;
            } else {
              recordBuilder_.addAllMessages(other.record_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> record_ =
        java.util.Collections.emptyList();
      private void ensureRecordIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          record_ = new java.util.ArrayList<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord>(record_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> recordBuilder_;

      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> getRecordList() {
        if (recordBuilder_ == null) {
          return java.util.Collections.unmodifiableList(record_);
        } else {
          return recordBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public int getRecordCount() {
        if (recordBuilder_ == null) {
          return record_.size();
        } else {
          return recordBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord getRecord(int index) {
        if (recordBuilder_ == null) {
          return record_.get(index);
        } else {
          return recordBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder setRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.set(index, value);
          onChanged();
        } else {
          recordBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder setRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.set(index, builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.add(value);
          onChanged();
        } else {
          recordBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord value) {
        if (recordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordIsMutable();
          record_.add(index, value);
          onChanged();
        } else {
          recordBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.add(builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addRecord(
          int index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder builderForValue) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.add(index, builderForValue.build());
          onChanged();
        } else {
          recordBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder addAllRecord(
          java.lang.Iterable<? extends org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord> values) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, record_);
          onChanged();
        } else {
          recordBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder clearRecord() {
        if (recordBuilder_ == null) {
          record_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          recordBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public Builder removeRecord(int index) {
        if (recordBuilder_ == null) {
          ensureRecordIsMutable();
          record_.remove(index);
          onChanged();
        } else {
          recordBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder getRecordBuilder(
          int index) {
        return getRecordFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder getRecordOrBuilder(
          int index) {
        if (recordBuilder_ == null) {
          return record_.get(index);  } else {
          return recordBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public java.util.List<? extends org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
           getRecordOrBuilderList() {
        if (recordBuilder_ != null) {
          return recordBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(record_);
        }
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder addRecordBuilder() {
        return getRecordFieldBuilder().addBuilder(
            org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder addRecordBuilder(
          int index) {
        return getRecordFieldBuilder().addBuilder(
            index, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .gmsreadout.ScanRecord record = 1;</code>
       */
      public java.util.List<org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder> 
           getRecordBuilderList() {
        return getRecordFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder> 
          getRecordFieldBuilder() {
        if (recordBuilder_ == null) {
          recordBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecord.Builder, org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ScanRecordOrBuilder>(
                  record_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          record_ = null;
        }
        return recordBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gmsreadout.ContactRecords)
    }

    // @@protoc_insertion_point(class_scope:gmsreadout.ContactRecords)
    private static final org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords();
    }

    public static org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ContactRecords>
        PARSER = new com.google.protobuf.AbstractParser<ContactRecords>() {
      @java.lang.Override
      public ContactRecords parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactRecords(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContactRecords> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContactRecords> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.tosl.coronawarncompanion.gmsreadout.ContactRecordsProtos.ContactRecords getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gmsreadout_ScanRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gmsreadout_ScanRecord_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gmsreadout_ContactRecords_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gmsreadout_ContactRecords_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ContactRecords.proto\022\ngmsreadout\":\n\nSc" +
      "anRecord\022\021\n\ttimestamp\030\001 \001(\r\022\014\n\004rssi\030\003 \001(" +
      "\003\022\013\n\003aem\030\004 \001(\014\"8\n\016ContactRecords\022&\n\006reco" +
      "rd\030\001 \003(\0132\026.gmsreadout.ScanRecordB?\n\'org." +
      "tosl.coronawarncompanion.gmsreadoutB\024Con" +
      "tactRecordsProtos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gmsreadout_ScanRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gmsreadout_ScanRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gmsreadout_ScanRecord_descriptor,
        new java.lang.String[] { "Timestamp", "Rssi", "Aem", });
    internal_static_gmsreadout_ContactRecords_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gmsreadout_ContactRecords_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gmsreadout_ContactRecords_descriptor,
        new java.lang.String[] { "Record", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
